name: Python application with file generation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install holidays
        pip install openpyxl
        pip install wython

    - name: Run Python script to generate ics files
      run: |
        python A9.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: generated-files  # Artifact 的名字
        path: output/  # 指定保存的文件或目录

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add output/
        git commit -m "update"
        git push origin main

